version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: chatapp
    restart: always
    build: .
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/chatdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    container_name: postgresqldb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chatdb
