version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: chatapp
    restart: always
    build: .
    ports:
      - 8081:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3307
  mysql:
    image: mysql:8
    ports:
      - 3307:3307
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=chatapp_user
      - MYSQL_DATABASE=chatapp_db
